import type { Metadata } from 'next';
import { LegalPage } from '@/components/legal-page';

export const metadata: Metadata = {
  title: 'Official Domains — Direct Connect Pay',
  description: 'Authorized domains and properties operated by Direct Connect Pay (DCP).',
};

const productionDomains = [
  {
    domain: 'directconnectpay.com',
    purpose: 'Primary marketing and corporate website',
    status: 'Production',
  },
  {
    domain: 'www.directconnectpay.com',
    purpose: 'Primary marketing and corporate website (www)',
    status: 'Production',
  },
];

const platformDomains = [
  {
    domain: '*.vercel.app',
    purpose: 'Merchant dashboard and web application (hosted on Vercel)',
    status: 'Production / staging',
  },
  {
    domain: '*.up.railway.app',
    purpose: 'DCP REST API and backend services (hosted on Railway)',
    status: 'Production / staging',
  },
];

export default function DomainsPage() {
  return (
    <LegalPage title="Official Domains" lastUpdated="June 16, 2026">
      <p>
        Direct Connect Pay (&ldquo;DCP,&rdquo; &ldquo;we,&rdquo; &ldquo;us&rdquo;) operates only the domains and
        subdomains listed on this page. Use this list to verify you are interacting with an authorized DCP
        property before entering credentials, API keys, or payment information.
      </p>

      <h2>Corporate &amp; marketing</h2>
      <DomainTable rows={productionDomains} />

      <h2>Platform &amp; API</h2>
      <p>
        Merchant dashboard, onboarding, and API endpoints may be served from the following infrastructure
        domains. Your deployed instance will use a specific hostname within these patterns.
      </p>
      <DomainTable rows={platformDomains} />

      <h2>Reporting impersonation</h2>
      <p>
        If you believe a website, email, or application is impersonating Direct Connect Pay, do not enter
        sensitive information. Contact us through the official website at{' '}
        <a href="https://www.directconnectpay.com" target="_blank" rel="noopener noreferrer">
          directconnectpay.com
        </a>{' '}
        and report the suspicious domain, URL, and any messages you received.
      </p>

      <h2>Subdomain policy</h2>
      <ul>
        <li>We do not request API keys, wallet seed phrases, or private keys via email or SMS.</li>
        <li>Legitimate DCP login uses your merchant API key only on our dashboard or documented API endpoints.</li>
        <li>Payment flows are non-custodial — we generate receive addresses and tags; we do not hold customer funds.</li>
        <li>Third-party integrations (e.g. wallet apps) should link only to URIs generated by the DCP API.</li>
      </ul>

      <h2>Changes</h2>
      <p>
        We may add or retire domains as infrastructure changes. Material updates will be reflected on this page.
        Continued use of the platform after updates constitutes acknowledgment of the revised list.
      </p>
    </LegalPage>
  );
}

function DomainTable({
  rows,
}: {
  rows: { domain: string; purpose: string; status: string }[];
}) {
  return (
    <div className="legal-table-wrap my-6">
      <table className="table">
        <thead>
          <tr>
            <th>Domain</th>
            <th>Purpose</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          {rows.map((row) => (
            <tr key={row.domain}>
              <td className="mono text-dcp-cyan">{row.domain}</td>
              <td>{row.purpose}</td>
              <td>
                <span className="dcp-badge text-[10px]">{row.status}</span>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}